### ISSUE TITLE
To Do List for full 1.30 Compatibility

### ISSUE THREAD

**Issue by UndeadWizard** [UndeadWizard/Occultus-Insaniam#36]
* ~New Trade-nodes~
  -~make Mu nodes finally~
* ~Fix Atlantean Mission Tree~
   -~Alter the Diplomatic Priority and Deal with Foreigners missions~
   -Maybe add rewards to reclaim missions ###Zeph edit: you can probably cross this one###
* ~Fix OI Institutions~
  -Alter the existing events, and create a new ones
* ~Alter Yazdeism~
* ~Fix Atlanic~
* ~Fiigure out why Emperor Crashes game~
* ~Fix Religious Icons~

**Comment by Zephyrum** [comment]
god help you

**Comment by Zephyrum** [comment]
or allah, for that matter
