### ISSUE TITLE
tell undead to delete the northern islands every day

### ISSUE THREAD

**Issue by Zephyrum** [UndeadWizard/Occultus-Insaniam#39]
it's important

**Comment by Zephyrum** [comment]
@UndeadWizard delete the northern islands

**Comment by Zephyrum** [comment]
@UndeadWizard delete the northern islands

**Comment by Zephyrum** [comment]
@UndeadWizard delete the northern islands

**Comment by Zephyrum** [comment]
@UndeadWizard delete the northern islands

**Comment by Zephyrum** [comment]
@UndeadWizard delete the northern islands

**Comment by Zephyrum** [comment]
@UndeadWizard delete the northern islands

**Comment by Zephyrum** [comment]
@UndeadWizard delete the northern islands
(muscle memory had me click first issue from top-to-bottom and I almost put this in the cult issue...)

**Comment by Zephyrum** [comment]
@UndeadWizard delete the northern islands

**Comment by Zephyrum** [comment]
@UndeadWizard delete the northern islands and don't listen to relm

**Comment by Zephyrum** [comment]
@UndeadWizard delete the northern islands

**Comment by Zephyrum** [comment]
@UndeadWizard delete the northern islands; better late than never

**Comment by Zephyrum** [comment]
@UndeadWizard delete the northern islands, I miss notsobot

**Comment by Zephyrum** [comment]
@UndeadWizard delete the northern islands, thanks for posting in oi channels and indirectly reminding me

**Comment by Zephyrum** [comment]
@UndeadWizard delete the northern islands

**Comment by Zephyrum** [comment]
@UndeadWizard delete the northern islands

**Comment by neothiamin** [comment]
big poggerino

**Comment by neothiamin** [comment]
![belugapog](https://user-images.githubusercontent.com/8920936/110844135-0ade6c00-8277-11eb-9c14-eabbb18094a1.png)

**Comment by neothiamin** [comment]
![POG2](https://user-images.githubusercontent.com/8920936/110844171-16319780-8277-11eb-9ec8-5c90cc75f010.png)

**Comment by neothiamin** [comment]
![POGcumber3](https://user-images.githubusercontent.com/8920936/110844193-192c8800-8277-11eb-904a-046cc03d05cf.png)

**Comment by neothiamin** [comment]
@UndeadWizard delete the northern islands

**Comment by Zephyrum** [comment]
@UndeadWizard delete the northern islands

**Comment by Zephyrum** [comment]
@UndeadWizard delete the northern islands

**Comment by Zephyrum** [comment]
It was inevitable that I'd fail to uphold a schedule
But I sure as fuck will keep trying
@UndeadWizard delete the northern islands

**Comment by Zephyrum** [comment]
GET UP AND TRY AGAIN
@UndeadWizard delete the northern islands

**Comment by Zephyrum** [comment]
I have failed my mission
