### ISSUE TITLE
Reasons why I hate Paradox Updates

### ISSUE THREAD

**Issue by UndeadWizard** [UndeadWizard/Occultus-Insaniam#43]
* ~~Need to move another 102 province IDs~~
* Look to see what I can steal from the polynesians to give to the MUlynesians
* ~~Add new provinces to province map~~
* Alter culture file
* Alter trade nodes for new provinces
* Change trade companies for new provinces
* Fix the random but inevitable bugs that arise from the paradox updates
* Delete the Northern Islands

**Comment by Zephyrum** [comment]
tried a stealth edit but github actually rats you out, sadge
![image](https://user-images.githubusercontent.com/3027827/117051676-30bf4480-aced-11eb-9e27-6e26164664be.png)
