### ISSUE TITLE
 Atlantean Mission Tree

### ISSUE THREAD

**Issue by UndeadWizard** [UndeadWizard/Occultus-Insaniam#7]
To be honest it'd probably look a lot like a TO one when it's all said and done.

**Comment by Zephyrum** [comment]
https://cdn.discordapp.com/attachments/572633928545075202/630783130697203725/65f9d14745154ce28849d3195d296ff9.png
https://cdn.discordapp.com/attachments/572633928545075202/630783138565455877/3942877622dda66038386f8f5445c6ff.png
