### ISSUE TITLE
Antillia Base Package

### ISSUE THREAD

**Issue by UndeadWizard** [UndeadWizard/Occultus-Insaniam#9]
Needs 3 flavor events, Church Aspects that make sense, snazzy flags, and an alternate down the line to being a Theocracy.

ZEPH EDIT: And Missions!

UNDEAD EDIT: Meh close enough, I'm counting the discovery events as Flavor

**Comment by UndeadWizard** [comment]
Made a random collection of Antillian flags, will figure out if I like them or now when I get home. Might need someone else to make Cross-flags since I look at them "meh"-ly

**Comment by Zephyrum** [comment]
Antillia formable + flag, presumably. NIs in different issue.

**Comment by Zephyrum** [comment]
Relevant images for mission tree

Generic Antillian ("part 1"): https://cdn.discordapp.com/attachments/589643121369808905/625925768245018635/fc9869126103dc904313bd32b7ca93b6.png

Antillian Formable ("part 2"): https://cdn.discordapp.com/attachments/589643121369808905/625925779431358465/e991ed5b521ff952a573f5f46b2a880e.png
